name: create-k8s-test-resources

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create on K8S
      uses: kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_TEST }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: apply -f .k8s/test_server
